- src: https://github.com/xrowgmbh/ansible-role-ansible.git
  name: ansible
  
- src: https://github.com/xrowgmbh/ansible-role-python.git
  name: python

- src: https://github.com/xrowgmbh/ansible-role-scl.git
  name: scl
